sy on
se nu rnu so=8 bs=2 sw=4 ts=4 sts=4 hls ls=2 cin acd mouse=a et
map <F9> :w<bar>!g++ "%" -o %:r -std=c++20 -Wall -Wextra -Wshadow -Wconversion -O2 -Dzisk -g -fsanitize=address,undefined<CR>
map <F8> :!./%:r<CR>
inoremap {<CR> {<CR>}<ESC>O
ca Hash w !cpp -dD -P -fpreprocessed \| tr -d '[:space:]' \| md5sum \| cut -c-6
inoremap fj <ESC>
vnoremap fj <ESC>
" -D_GLIBCXX_ASSERTIONS, -D_GLIBCXX_DEBUG
