sy on
se nocp nu rnu so=8 bs=2 sw=4 ts=4 sts=4 hls ls=2 cin acd mouse=a et
map <F9> :w<bar>!g++ "%" -o %:r -std=c++20 -O2 -Wall -Wextra -Wshadow -Wconversion -DMEOW -g -fsanitize=address,undefined<CR>
map <F8> :!./%:r<CR>
inoremap {<CR> {<CR>}<ESC>ko
inoremap fj <ESC>
vnoremap fj <ESC>
" ca Hash w !cpp -dD -P -fpreprocessed \\| tr -d '[:space:]' \\| md5sum \\| cut -c-6
